### ISSUE TITLE
New 'organelle' assembly index variable has no type

### ISSUE THREAD

**Issue by Euphrasiologist** [genomehubs/goat-data#26]
I assume it's type keyword?

**Comment by sujaikumar** [comment]
Yes, based on this section in https://github.com/genomehubs/genomehubs/blob/develop/src/genomehubs/templates/organelle.types.yaml
```
  organelle:
    constraint:
      enum:
      - nucleus
      - mitochondrion
      - chloroplast
      - plastid
      - apicoplast
    default: '{{organelle}}'
    display_group: general
    source: NCBI
    source_url_stub: https://www.ncbi.nlm.nih.gov/nuccore/
```
We'll add `type: keyword` - thanks!
